name: Laravel

on: [push]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: postgres:10.8
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password
          POSTGRES_DB: admin

    steps:
      - uses: actions/checkout@v1
      - name: Copy .env
        run: cp .env.ci .env
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Create Database
        run: php artisan migrate

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: php ./vendor/bin/phpunit --debug
